// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account/v1/account.proto

package v1

import (
	fmt "fmt"
	math "math"
	pbentity "proxima/app/user/api/pbentity"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RegisterReq struct {
	Passport             string   `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterReq) Reset()         { *m = RegisterReq{} }
func (m *RegisterReq) String() string { return proto.CompactTextString(m) }
func (*RegisterReq) ProtoMessage()    {}
func (*RegisterReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6e54449a5ba7eb, []int{0}
}

func (m *RegisterReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterReq.Unmarshal(m, b)
}
func (m *RegisterReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterReq.Marshal(b, m, deterministic)
}
func (m *RegisterReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterReq.Merge(m, src)
}
func (m *RegisterReq) XXX_Size() int {
	return xxx_messageInfo_RegisterReq.Size(m)
}
func (m *RegisterReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterReq proto.InternalMessageInfo

func (m *RegisterReq) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func (m *RegisterReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *RegisterReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterRes struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterRes) Reset()         { *m = RegisterRes{} }
func (m *RegisterRes) String() string { return proto.CompactTextString(m) }
func (*RegisterRes) ProtoMessage()    {}
func (*RegisterRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6e54449a5ba7eb, []int{1}
}

func (m *RegisterRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterRes.Unmarshal(m, b)
}
func (m *RegisterRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterRes.Marshal(b, m, deterministic)
}
func (m *RegisterRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterRes.Merge(m, src)
}
func (m *RegisterRes) XXX_Size() int {
	return xxx_messageInfo_RegisterRes.Size(m)
}
func (m *RegisterRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterRes.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterRes proto.InternalMessageInfo

func (m *RegisterRes) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginReq struct {
	Passport             string   `protobuf:"bytes,1,opt,name=passport,proto3" json:"passport,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6e54449a5ba7eb, []int{2}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6e54449a5ba7eb, []int{3}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InfoReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoReq) Reset()         { *m = InfoReq{} }
func (m *InfoReq) String() string { return proto.CompactTextString(m) }
func (*InfoReq) ProtoMessage()    {}
func (*InfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6e54449a5ba7eb, []int{4}
}

func (m *InfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoReq.Unmarshal(m, b)
}
func (m *InfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoReq.Marshal(b, m, deterministic)
}
func (m *InfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoReq.Merge(m, src)
}
func (m *InfoReq) XXX_Size() int {
	return xxx_messageInfo_InfoReq.Size(m)
}
func (m *InfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_InfoReq proto.InternalMessageInfo

func (m *InfoReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type InfoRes struct {
	User                 *pbentity.User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *InfoRes) Reset()         { *m = InfoRes{} }
func (m *InfoRes) String() string { return proto.CompactTextString(m) }
func (*InfoRes) ProtoMessage()    {}
func (*InfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_df6e54449a5ba7eb, []int{5}
}

func (m *InfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRes.Unmarshal(m, b)
}
func (m *InfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRes.Marshal(b, m, deterministic)
}
func (m *InfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRes.Merge(m, src)
}
func (m *InfoRes) XXX_Size() int {
	return xxx_messageInfo_InfoRes.Size(m)
}
func (m *InfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRes proto.InternalMessageInfo

func (m *InfoRes) GetUser() *pbentity.User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterReq)(nil), "account.v1.RegisterReq")
	proto.RegisterType((*RegisterRes)(nil), "account.v1.RegisterRes")
	proto.RegisterType((*LoginReq)(nil), "account.v1.LoginReq")
	proto.RegisterType((*LoginRes)(nil), "account.v1.LoginRes")
	proto.RegisterType((*InfoReq)(nil), "account.v1.InfoReq")
	proto.RegisterType((*InfoRes)(nil), "account.v1.InfoRes")
}

func init() {
	proto.RegisterFile("account/v1/account.proto", fileDescriptor_df6e54449a5ba7eb)
}

var fileDescriptor_df6e54449a5ba7eb = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x52, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x6d, 0x42, 0x43, 0xc3, 0x55, 0xea, 0xe0, 0x56, 0x22, 0x8a, 0x84, 0x5a, 0x3c, 0xb1, 0x10,
	0xab, 0x41, 0xac, 0x48, 0x74, 0x43, 0x62, 0x8a, 0xc4, 0x02, 0x93, 0xdb, 0x98, 0xca, 0x82, 0xc6,
	0xc6, 0x76, 0x0b, 0xfc, 0x17, 0x1f, 0x88, 0xec, 0xc4, 0x4d, 0x86, 0x30, 0xb1, 0xf9, 0xdd, 0x7b,
	0x7e, 0x77, 0xf7, 0x74, 0x90, 0xd0, 0xcd, 0x46, 0xec, 0x2b, 0x43, 0x0e, 0x4b, 0xd2, 0x3c, 0x33,
	0xa9, 0x84, 0x11, 0x08, 0x3c, 0x3c, 0x2c, 0xd3, 0xa9, 0x5c, 0xb3, 0xca, 0x70, 0xf3, 0x4d, 0xf6,
	0x9a, 0xa9, 0x5a, 0x80, 0x5f, 0x60, 0x5c, 0xb0, 0x2d, 0xd7, 0x86, 0xa9, 0x82, 0x7d, 0xa0, 0x14,
	0x62, 0x49, 0xb5, 0x96, 0x42, 0x99, 0x24, 0x58, 0x04, 0x57, 0x67, 0xc5, 0x11, 0x7b, 0xee, 0x53,
	0xa8, 0x32, 0x09, 0x5b, 0xce, 0x62, 0x34, 0x83, 0x88, 0xed, 0x28, 0x7f, 0x4f, 0x4e, 0x1c, 0x51,
	0x03, 0x7c, 0xd1, 0x35, 0xd7, 0x68, 0x02, 0x21, 0x2f, 0x9d, 0x6d, 0x54, 0x84, 0xbc, 0xc4, 0x2b,
	0x88, 0x1f, 0xc5, 0x96, 0x57, 0xff, 0x68, 0x8c, 0x17, 0x47, 0x0f, 0x6d, 0x87, 0x30, 0xe2, 0x8d,
	0x55, 0x8d, 0x41, 0x0d, 0xf0, 0x1c, 0x46, 0x0f, 0xd5, 0xab, 0xb0, 0x4d, 0xfa, 0x05, 0xd7, 0x5e,
	0xa0, 0x11, 0x86, 0xa1, 0xcd, 0xc6, 0xf1, 0xe3, 0x7c, 0x92, 0xf9, 0xc4, 0xb2, 0x27, 0xcd, 0x54,
	0xe1, 0xb8, 0xfc, 0x27, 0x80, 0xd1, 0x7d, 0x9d, 0x2a, 0xba, 0x83, 0xd8, 0x2f, 0x88, 0xce, 0xb3,
	0x36, 0xeb, 0xac, 0x93, 0x69, 0xfa, 0x07, 0xa1, 0xf1, 0x00, 0xdd, 0x42, 0xe4, 0xa6, 0x47, 0xb3,
	0xae, 0xc6, 0x87, 0x92, 0xf6, 0x55, 0xed, 0xb7, 0x1c, 0x86, 0x76, 0x62, 0x34, 0xed, 0xf2, 0xcd,
	0x92, 0x69, 0x4f, 0x51, 0xe3, 0xc1, 0xea, 0xf2, 0x79, 0x2e, 0x95, 0xf8, 0xe2, 0x3b, 0x4a, 0xa8,
	0x94, 0xee, 0x04, 0x08, 0x95, 0x9c, 0xb4, 0xa7, 0xb3, 0x3e, 0x75, 0x27, 0x71, 0xf3, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x7f, 0xa0, 0xee, 0x33, 0x4f, 0x02, 0x00, 0x00,
}
