// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbentity/user.proto

package pbentity

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   uint32                 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Passport             string                 `protobuf:"bytes,2,opt,name=Passport,proto3" json:"Passport,omitempty"`
	Password             string                 `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	Email                string                 `protobuf:"bytes,4,opt,name=Email,proto3" json:"Email,omitempty"`
	CreateAt             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreateAt,proto3" json:"CreateAt,omitempty"`
	UpdateAt             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdateAt,proto3" json:"UpdateAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_16f927528f2d185e, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetPassport() string {
	if m != nil {
		return m.Passport
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetCreateAt() *timestamppb.Timestamp {
	if m != nil {
		return m.CreateAt
	}
	return nil
}

func (m *User) GetUpdateAt() *timestamppb.Timestamp {
	if m != nil {
		return m.UpdateAt
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "pbentity.User")
}

func init() {
	proto.RegisterFile("pbentity/user.proto", fileDescriptor_16f927528f2d185e)
}

var fileDescriptor_16f927528f2d185e = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x3f, 0x4b, 0xc4, 0x30,
	0x18, 0xc6, 0x49, 0xbd, 0x3b, 0x6a, 0x44, 0x87, 0xe8, 0x10, 0x0a, 0x72, 0xc5, 0xa9, 0x53, 0x02,
	0x0a, 0xee, 0x2a, 0x0e, 0xb7, 0x49, 0xf1, 0x16, 0xb7, 0x94, 0xc4, 0x12, 0x68, 0xcc, 0x4b, 0xf2,
	0x16, 0xf5, 0x7b, 0xfa, 0x81, 0xa4, 0x09, 0xa9, 0xa3, 0xe3, 0xf3, 0xe7, 0x07, 0x0f, 0x0f, 0xbd,
	0x84, 0xc1, 0x7c, 0xa0, 0xc5, 0x6f, 0x39, 0x47, 0x13, 0x04, 0x04, 0x8f, 0x9e, 0xd5, 0xc5, 0x6c,
	0xf6, 0xa3, 0xf7, 0xe3, 0x64, 0x64, 0xf2, 0x87, 0xf9, 0x5d, 0xa2, 0x75, 0x26, 0xa2, 0x72, 0x90,
	0xab, 0x37, 0x3f, 0x84, 0x6e, 0x8e, 0xd1, 0x04, 0x76, 0x41, 0xab, 0x83, 0xe6, 0xa4, 0x25, 0xdd,
	0x79, 0x5f, 0x1d, 0x34, 0x6b, 0x68, 0xfd, 0xa2, 0x62, 0x04, 0x1f, 0x90, 0x57, 0x2d, 0xe9, 0x4e,
	0xfb, 0x55, 0x97, 0xec, 0xd3, 0x07, 0xcd, 0x4f, 0xfe, 0xb2, 0x45, 0xb3, 0x2b, 0xba, 0x7d, 0x76,
	0xca, 0x4e, 0x7c, 0x93, 0x82, 0x2c, 0xd8, 0x3d, 0xad, 0x9f, 0x82, 0x51, 0x68, 0x1e, 0x90, 0x6f,
	0x5b, 0xd2, 0x9d, 0xdd, 0x36, 0x22, 0x4f, 0x13, 0x65, 0x9a, 0x78, 0x2d, 0xd3, 0xfa, 0xb5, 0xbb,
	0x70, 0x47, 0xd0, 0x99, 0xdb, 0xfd, 0xcf, 0x95, 0xee, 0xe3, 0xfe, 0xed, 0x1a, 0x82, 0xff, 0xb2,
	0x4e, 0x49, 0x05, 0x90, 0xbe, 0x91, 0x0a, 0xac, 0x2c, 0xc7, 0x0c, 0xbb, 0x84, 0xdf, 0xfd, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x53, 0x40, 0x08, 0x3f, 0x40, 0x01, 0x00, 0x00,
}
